### ISSUE TITLE
你好，什么时候公布代码

### ISSUE THREAD

**Issue by BeibeiIsFreshman** [BellyBeauty/MDSAM#1]

**Comment by BellyBeauty** [comment]
这周内代码和论文中提到的512*512和384*384分辨率的权重都会上传，相关的指南也会在readme文件中放出

**Comment by fak111** [comment]
come on!!

**Comment by BellyBeauty** [comment]
训练和测试代码目前已上传，如果代码中存在问题或是有疑惑的话，可以发送邮件到gaosx@dlut.mail.edu.cn或者是在issue中提问
